// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: M5Core2_SFB

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BGmainS2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_BGmainS2, 320);
    lv_obj_set_height(ui_BGmainS2, 240);
    lv_obj_set_align(ui_BGmainS2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BGmainS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BGmainS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BGmainS2, lv_color_hex(0x723232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BGmainS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BGmainS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleS2 = lv_label_create(ui_BGmainS2);
    lv_obj_set_width(ui_TitleS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TitleS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleS2, 0);
    lv_obj_set_y(ui_TitleS2, -95);
    lv_obj_set_align(ui_TitleS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TitleS2, "Manueller Flow");
    lv_obj_set_style_text_color(ui_TitleS2, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleS2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrowS2 = lv_label_create(ui_BGmainS2);
    lv_obj_set_width(ui_ArrowS2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrowS2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrowS2, -140);
    lv_obj_set_y(ui_ArrowS2, 0);
    lv_obj_set_align(ui_ArrowS2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrowS2, "<");
    lv_obj_set_style_text_color(ui_ArrowS2, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrowS2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrowS2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenSwitchS2 = lv_btn_create(ui_BGmainS2);
    lv_obj_set_width(ui_ScreenSwitchS2, 55);
    lv_obj_set_height(ui_ScreenSwitchS2, 125);
    lv_obj_set_x(ui_ScreenSwitchS2, -125);
    lv_obj_set_y(ui_ScreenSwitchS2, 0);
    lv_obj_set_align(ui_ScreenSwitchS2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenSwitchS2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScreenSwitchS2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenSwitchS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenSwitchS2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSwitchS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScreenSwitchS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ScreenSwitchS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ScreenSwitchS2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BG_Slider = lv_obj_create(ui_BGmainS2);
    lv_obj_set_width(ui_BG_Slider, 200);
    lv_obj_set_height(ui_BG_Slider, 60);
    lv_obj_set_x(ui_BG_Slider, 0);
    lv_obj_set_y(ui_BG_Slider, 15);
    lv_obj_set_align(ui_BG_Slider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BG_Slider, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BG_Slider, lv_color_hex(0x6D5338), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BG_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManFlowSlider = lv_slider_create(ui_BG_Slider);
    lv_slider_set_range(ui_ManFlowSlider, 0, 140);
    lv_slider_set_value(ui_ManFlowSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_ManFlowSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_ManFlowSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_ManFlowSlider, 150);
    lv_obj_set_height(ui_ManFlowSlider, 10);
    lv_obj_set_align(ui_ManFlowSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ManFlowSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManFlowSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ManFlowSlider, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ManFlowSlider, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ManFlowSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ManFlowSlider, lv_color_hex(0x8E8E8E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManFlowSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ManFlowSlider, lv_color_hex(0xD87900), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManFlowSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ManFlowVal = lv_label_create(ui_BGmainS2);
    lv_obj_set_width(ui_ManFlowVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManFlowVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManFlowVal, 0);
    lv_obj_set_y(ui_ManFlowVal, -40);
    lv_obj_set_align(ui_ManFlowVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManFlowVal, "Value");
    lv_obj_set_style_text_color(ui_ManFlowVal, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ManFlowVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ManFlowVal, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonM = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_buttonM, 100);
    lv_obj_set_height(ui_buttonM, 50);
    lv_obj_set_x(ui_buttonM, -70);
    lv_obj_set_y(ui_buttonM, 80);
    lv_obj_set_align(ui_buttonM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonM, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonM, lv_color_hex(0x6D5338), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonM, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonM, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelM = lv_label_create(ui_buttonM);
    lv_obj_set_width(ui_labelM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelM, "-");
    lv_obj_set_style_text_font(ui_labelM, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonP = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_buttonP, 100);
    lv_obj_set_height(ui_buttonP, 50);
    lv_obj_set_x(ui_buttonP, 70);
    lv_obj_set_y(ui_buttonP, 80);
    lv_obj_set_align(ui_buttonP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonP, lv_color_hex(0x6D5338), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_buttonP, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_buttonP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_buttonP, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelP = lv_label_create(ui_buttonP);
    lv_obj_set_width(ui_labelP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelP, "+");
    lv_obj_set_style_text_font(ui_labelP, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScreenSwitchS2, ui_event_ScreenSwitchS2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonM, ui_event_buttonM, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_buttonP, ui_event_buttonP, LV_EVENT_ALL, NULL);

}
