// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: M5Core2_SFB

#ifndef _M5CORE2_SFB_UI_H
#define _M5CORE2_SFB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_BGmainS1;
extern lv_obj_t * ui_TitleS1;
void ui_event_ScreenSwitchS1(lv_event_t * e);
extern lv_obj_t * ui_ScreenSwitchS1;
extern lv_obj_t * ui_ArrowS1;
extern lv_obj_t * ui_BGStatus;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_Com;
extern lv_obj_t * ui_TempVal;
extern lv_obj_t * ui_ComValGreen;
extern lv_obj_t * ui_ComValRed;
extern lv_obj_t * ui_BG_Flow;
extern lv_obj_t * ui_SollFlow;
extern lv_obj_t * ui_IstFlow;
extern lv_obj_t * ui_SollFlowMan;
extern lv_obj_t * ui_SollFlowManVal;
extern lv_obj_t * ui_IstFlowVal;
extern lv_obj_t * ui_SollFlowVal;
extern lv_obj_t * ui_FlowTitle;
void ui_event_RCmode(lv_event_t * e);
extern lv_obj_t * ui_RCmode;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_BGmainS2;
extern lv_obj_t * ui_TitleS2;
extern lv_obj_t * ui_ArrowS2;
void ui_event_ScreenSwitchS2(lv_event_t * e);
extern lv_obj_t * ui_ScreenSwitchS2;
extern lv_obj_t * ui_BG_Slider;
extern lv_obj_t * ui_ManFlowSlider;
extern lv_obj_t * ui_ManFlowVal;
void ui_event_buttonM(lv_event_t * e);
extern lv_obj_t * ui_buttonM;
extern lv_obj_t * ui_labelM;
void ui_event_buttonP(lv_event_t * e);
extern lv_obj_t * ui_buttonP;
extern lv_obj_t * ui_labelP;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
